version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mars_lab
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p123456",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - marslab-network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    volumes:
      - ./mars-lab:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mars_lab
      DB_USERNAME: root
      DB_PASSWORD: 123456
    restart: always
    networks:
      - marslab-network

  nextjs:
    build:
      context: ./marslab-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./marslab-next:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://laravel:80/api
      DATABASE_URL: mysql://root:123456@mysql:3306/mars_lab
    restart: always
    depends_on:
      - laravel
    networks:
      - marslab-network

networks:
  marslab-network:
    driver: bridge

volumes:
  mysql_data:
